// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "cities of sigmar",
    warscrolls: {
        "Pontifex Zenestra" : {
            baseSize: "90x52mm",
            notes: "",
        },
        "Assassin" : {
            baseSize: "25mm",
            notes: "",
        },
        "Battlemage" : {
            baseSize: "25mm",
            notes: "",
        },
        "Battlemage on Griffon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Black Ark Corsairs" : {
            baseSize: "25mm",
            notes: "",
        },
        "Black Ark Fleetmaster" : {
            baseSize: "25mm",
            notes: "",
        },
        "Black Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Bleakswords" : {
            baseSize: "25mm",
            notes: "",
        },
        "Celestial Hurricanum" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Cogsmith" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dark Riders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Darkshards" : {
            baseSize: "25mm",
            notes: "",
        },
        "Demigryph Knights" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Doralia ven Denst" : {
            baseSize: "28mm",
            notes: "",
        },
        "Drakespawn Chariots" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Drakespawn Knights" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Dreadlord on Black Dragon" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Dreadspears" : {
            baseSize: "25mm",
            notes: "",
        },
        "Tahlia Vedra" : {
            baseSize: "100mm",
            notes: "",
        },
        "Executioners" : {
            baseSize: "25mm",
            notes: "",
        },
        "Flagellants" : {
            baseSize: "25mm",
            notes: "",
        },
        "Fusil-Major on Ogor Warhulk" : {
            baseSize: "50mm",
            notes: "",
        },
        "Freeguild Marshal and Relic Envoy" : {
            baseSize: "1x32mm, 1x28mm",
            notes: "",
        },
        "Freeguild Cavalier-Marshal" : {
            baseSize: "75x42mm",
            notes: "",
        },
        "Freeguild General on Griffon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Freeguild Steelhelms" : {
            baseSize: "25mm",
            notes: "",
        },
        "Freeguild Fusiliers" : {
            baseSize: "28mm",
            notes: "",
        },
        "Freeguild Command corps" : {
            baseSize: "1x25mm, 1x40mm, 4x28mm",
            notes: "",
        },
        "Freeguild Cavaliers" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Alchemite-Warforger" : {
            baseSize: "32mm",
            notes: "",
        },
        "Ironweld Great Cannon" : {
            baseSize: "90mm",
            notes: "",
        },
        "Galen ven Denst" : {
            baseSize: "28mm",
            notes: "",
        },
        "Gyrobombers" : {
            baseSize: "50mm",
            notes: "",
        },
        "Gyrocopters" : {
            baseSize: "50mm",
            notes: "",
        },
        "Hammerers" : {
            baseSize: "25mm",
            notes: "",
        },
        "Ironbreakers" : {
            baseSize: "25mm",
            notes: "",
        },
        "Irondrakes" : {
            baseSize: "25mm",
            notes: "",
        },
        "Kharibdyss" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Longbeards" : {
            baseSize: "25mm",
            notes: "",
        },
        "Luminark of Hysh" : {
            baseSize: "120 x 92mm",
            notes: "",
       },
        "Runelord" : {
            baseSize: "25mm",
            notes: "",
        },
        "Scourgerunner Chariots" : {
            baseSize: "120 x 92mm",
            notes: "",
       },
        "Sorceress" : {
            baseSize: "25mm",
            notes: "",
        },
        "Sorceress on Black Dragon" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Steam Tank" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "War Hydra" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Warden King" : {
            baseSize: "25mm",
            notes: "",
        },
    }
}
export default Warscrolls
