// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "flesheater courts",
    warscrolls: {
        "Abhorrant Archregent" : {
            baseSize: "40mm",
            notes: "",
        },
        "Abhorrant Ghoul King" : {
            baseSize: "32mm",
            notes: "",
        },
        "Abhorrant Ghoul King on Royal Terrorgheist" : {
            baseSize: "130mm",
            notes: "",
        },
        "Abhorrant Ghoul King on Royal Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Cadaverous Barricade" : {
            baseSize: "Custom base",
            notes: "",
        },
        "Chalice of Ushoran" : {
            baseSize: "50mm",
            notes: "",
        },
        "Corpsemare Stampede" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Crypt Flayers" : {
            baseSize: "50mm",
            notes: "",
        },
        "Crypt Ghast Courtier" : {
            baseSize: "32mm",
            notes: "",
        },
        "Crypt Ghouls" : {
            baseSize: "25mm",
            notes: "",
        },
        "Crypt Haunter Courtier" : {
            baseSize: "50mm",
            notes: "",
        },
        "Crypt Horrors" : {
            baseSize: "50mm",
            notes: "",
        },
        "Crypt Infernal Courtier" : {
            baseSize: "50mm",
            notes: "",
        },
        "Royal Terrorgheist" : {
            baseSize: "130mm",
            notes: "",
        },
        "Royal Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Varghulf Courtier" : {
            baseSize: "90x52mm",
            notes: "",
        },
        "Morbheg Knights" : {
            baseSize: "75x42mm",
            notes: "",
        },
        "Abhorrant Gorewarden" : {
            baseSize: "40mm",
            notes: "",
        },
        "Abhorrant Cardinal" : {
            baseSize: "32mm",
            notes: "",
        },
        "Marrowscroll Herald" : {
            baseSize: "32mm",
            notes: "",
        },
        "Cryptguard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Royal Beastflayers" : {
            baseSize: "3x25mm, 3x28mm, 2x32mm, 2x40mm",
            notes: "",
        },
    }
}
export default Warscrolls
